### ISSUE TITLE
No confirm password field in registration page #FR Bug

### ISSUE THREAD

**Issue by SiddharthaAlwala** [sweetypasupuleti/Student-Resource-Web-Application#1]
Confirm password field missing in registration page

**Comment by alekyamullapudi** [comment]
Issue resolved. Confirm Password field is usually used to prevent users from making mistakes while entering the password.
here is the code added to the registration page.

<div className='mb-3'>
                            <input
                                type="password"
                                id="confirm_password"
                                placeholder='Confirm Password'
                                name='confirm_password'
                                value={values.confirm_password}
                                onChange={handleInput}
                                className='form-control rounded-0'
                            />
                            {errors.confirm_password && <p className="text-danger">{errors.confirm_password}</p>}
                        </div>

<img width="468" alt="Picture1" src="https://github.com/sweetypasupuleti/Student-Resource-Web-Application/assets/146123273/401eafce-216f-4a87-a7d0-a20e07f7353e">
