### ISSUE TITLE
Page access #FR Bug

### ISSUE THREAD

**Issue by SiddharthaAlwala** [sweetypasupuleti/Student-Resource-Web-Application#13]
Admin page should not be accessed by users.

**Comment by sweetypasupuleti** [comment]
Issue has been resolved.

**Comment by sweetypasupuleti** [comment]
![Admin_bug](https://github.com/sweetypasupuleti/Student-Resource-Web-Application/assets/145917330/55c96843-3d55-4218-87fa-2e7af04f3516)
Fixed it
