### ISSUE TITLE
Adding events in calendar #FR Bug

### ISSUE THREAD

**Issue by SiddharthaAlwala** [sweetypasupuleti/Student-Resource-Web-Application#14]
Only admin can be able to add events in calendar.

**Comment by sweetypasupuleti** [comment]
Issue has been resolved.

**Comment by sweetypasupuleti** [comment]
![AddCalendar_bug](https://github.com/sweetypasupuleti/Student-Resource-Web-Application/assets/145917330/ea1f01fa-698c-48b3-b562-a94736f6f73d)
fixed it.
