### ISSUE TITLE
Inconsistent styling #NFR Bug

### ISSUE THREAD

**Issue by SiddharthaAlwala** [sweetypasupuleti/Student-Resource-Web-Application#15]
Course grids are inconsistent due to css errors.

**Comment by sweetypasupuleti** [comment]
Issue has been resolved.

**Comment by sweetypasupuleti** [comment]
![Courses_bug](https://github.com/sweetypasupuleti/Student-Resource-Web-Application/assets/145917330/66b765df-02c9-4146-b4e5-7d26bc83ca33)
Fixed it..
