### ISSUE TITLE
Quiz score #FR Bug

### ISSUE THREAD

**Issue by SiddharthaAlwala** [sweetypasupuleti/Student-Resource-Web-Application#17]
Score should be stored for each user based on their attempts.

**Comment by shivakumar70707** [comment]
Issue resolved.
Scores will be shown in report page for each user based on their attempts.
![image](https://github.com/sweetypasupuleti/Student-Resource-Web-Application/assets/143692066/32d38634-eae8-4c97-a1bc-5bcf3a49ce82)
