### ISSUE TITLE
Missing password strength indicator #NFR Bug

### ISSUE THREAD

**Issue by SiddharthaAlwala** [sweetypasupuleti/Student-Resource-Web-Application#2]
Missing password strength indicator in signup page

**Comment by alekyamullapudi** [comment]
Password strength indicators are a way to show users how strong their password is, using visual cues like color bars or text messages.
Following image is the code adding the password strength indicator to the signup page.

<img width="468" alt="image" src="https://github.com/sweetypasupuleti/Student-Resource-Web-Application/assets/146123273/14f21e26-783b-4a23-a2a6-8092750920c9">
