### ISSUE TITLE
Feedback message on successful registration #FR Bug

### ISSUE THREAD

**Issue by SiddharthaAlwala** [sweetypasupuleti/Student-Resource-Web-Application#3]
No message when the registration successful.

**Comment by alekyamullapudi** [comment]
Solved.
The message is added to the code.

<img width="468" alt="image" src="https://github.com/sweetypasupuleti/Student-Resource-Web-Application/assets/146123273/1384d1f3-32ab-4e58-87d8-767f281d8acc">
