### ISSUE TITLE
Static server URL #FR Bug

### ISSUE THREAD

**Issue by SiddharthaAlwala** [sweetypasupuleti/Student-Resource-Web-Application#4]
Server URL is static.

**Comment by Ravali07-1997** [comment]
Resolved.

![image](https://github.com/sweetypasupuleti/Student-Resource-Web-Application/assets/146063169/7d8eea15-f9e9-439d-b4fb-9e93dc77bbe3)
![image](https://github.com/sweetypasupuleti/Student-Resource-Web-Application/assets/146063169/d5864a68-4d53-40b9-a90b-e7510af18c56)
