### ISSUE TITLE
Accessibility #FR Bug

### ISSUE THREAD

**Issue by SiddharthaAlwala** [sweetypasupuleti/Student-Resource-Web-Application#6]
To improve accessibility, its essential to ensure that form elements are associated with their corresponding labels.

**Comment by Ravali07-1997** [comment]
Issue resolved.
![image](https://github.com/sweetypasupuleti/Student-Resource-Web-Application/assets/146063169/b8585d54-8078-445c-aae5-edb7a813b344)
